[package]
name = "lockbox"
version = "0.1.0"
description = "Nexus Protocol — Lockbox: claim-link transfers with expiry auto-refund."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lockbox"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
